### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by VkaSC** [VkaSC/todo-list#1]
@alimarchi vamos a realizar una lista de tareas

**Comment by VkaSC** [comment]
@alimarchi check listo

**Comment by alimarchi** [comment]
@VkaSC check hecho

**Comment by VkaSC** [comment]
@alimarchi check hecho

**Comment by alimarchi** [comment]
@VkaSC check installing hecho

**Comment by VkaSC** [comment]
@alimarchi  check deployment hecho

**Comment by alimarchi** [comment]
@VkaSC built with hecho

**Comment by VkaSC** [comment]
@alimarchi check author hecho

**Comment by alimarchi** [comment]
@VkaSC license listo

**Comment by VkaSC** [comment]
@alimarchi Desarrollo completado
