### ISSUE TITLE
README

### ISSUE THREAD

**Issue by alimarchi** [VkaSC/todo-list#2]
@VkaSC title listo

**Comment by VkaSC** [comment]
@alimarchi getting started hecho

**Comment by alimarchi** [comment]
@VkaSC prerequisites hecho

**Comment by VkaSC** [comment]
@alimarchi Installing hecho

**Comment by alimarchi** [comment]
@VkaSC deployment listo

**Comment by VkaSC** [comment]
@alimarchi built with terminado

**Comment by alimarchi** [comment]
@VkaSC authors listo

**Comment by VkaSC** [comment]
@alimarchi License hecho

**Comment by alimarchi** [comment]
@VkaSC desarrollo terminado, cierro issue.
